#!/bin/bash

# Copyright 2011 Red Hat Inc.
#
# This file is part of solenopsis
#
# solenopsis is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

noAntJars() {
	echo " "
	echo "ERROR:  No Ant jars found!!!!  Cannot run solenopsis!"
	echo " "
	exit 1
}

if [ ! -e /usr/share/solenopsis/ant/lib/ant/ ]
then
	noAntJars
fi

ANT_CLASSPATH=`find /usr/share/solenopsis/ant/lib/ant/ | tr -s '\n' ':'`

if [ "${ANT_CLASSPATH}" = "/usr/share/solenopsis/ant/lib/ant/:" ]
then
	noAntJars
fi

while [ $# -gt 0 ]
do
	if [ $1 = "--classpath" ]
	then
		shift

		# Hate preceeding colons in paths...
		if [ "${USER_CLASSPATH}" = "" ]
		then
			USER_CLASSPATH="$1"
		else
			USER_CLASSPATH="${USER_CLASSPATH}:$1"
		fi
	else
		SOLENOPSIS_ARGS="${SOLENOPSIS_ARGS} $1"
	fi

	shift
done

# Hate preceeding colons in paths...
if [ "${USER_CLASSPATH}" = "" ]
then
	CLASSPATH="${ANT_CLASSPATH}"
else
	CLASSPATH="${USER_CLASSPATH}:${ANT_CLASSPATH}"
fi

# Kick off ant...
java -classpath ${CLASSPATH} -Dant.home=/usr/share/solenopsis/ant org.apache.tools.ant.Main ${SOLENOPSIS_ARGS}