#!/bin/bash

# Copyright 2011 Red Hat Inc.
#
# This file is part of solenopsis
#
# solenopsis is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

# Emit help...
help() {
	echo " "
	echo "Usage:"
	echo "     bsolenopsis [--classpath user-class-path] [--antversion the-ant-version] [standard ant command line options]"
	echo " "
	exit 0
}

# Error out when there are no Ant jars found...
noAntJars() {
	echo " "
	echo "ERROR:  No Ant jars found!!!!  Cannot run solenopsis!"
	echo " "
	exit 1
}

# Default Ant script to run and Ant version to use...

# Trying to support OS/X users here.  The readline -f
# command is different under OS/X:
#     ABSOLUTE_HOME=`readlink -f ${BASH_SOURCE[0]}`
if [ -L  ${BASH_SOURCE[0]} ]
then
    COMPLETE_LINK=`ls -latr /usr/bin/bsolenopsis | cut -f 2 -d '>'`
    SCRIPT_HOME=`dirname ${COMPLETE_LINK}`
else
    SCRIPT_HOME=`dirname ${BASH_SOURCE[0]}`
fi

USER_FILE=${SCRIPT_HOME}/../ant/solenopsis.xml
ANT_VERSION=1.9.4

# Iterate over command line args...
while [ $# -gt 0 ]
do
	if [ $1 = "--classpath" ]
	then
		shift

		# Hate preceeding colons in paths...
		if [ "${USER_CLASSPATH}" = "" ]
		then
			USER_CLASSPATH="$1"
		else
			USER_CLASSPATH="${USER_CLASSPATH}:$1"
		fi
	elif [ $1 = "-f" ]
	then
		shift

		USER_FILE=$1
	elif [ $1 = "--antversion" ]
	then
		shift

		ANT_VERSION=$1
	elif [ $1 = "-h" -o $1 = "--help" ]
	then
		help
	else
		SOLENOPSIS_ARGS="${SOLENOPSIS_ARGS} $1"
	fi

	shift
done

# Make sure we have some version of Ant libraries
if [ ! -e ${SCRIPT_HOME}/../ant/lib/${ANT_VERSION} ]
then
	noAntJars
fi

ANT_CLASSPATH=`find ${SCRIPT_HOME}/../ant/lib/${ANT_VERSION} -name \*.jar | tr -s '\n' ':'`

# Make sure we have at least one jar...
if [ "${ANT_CLASSPATH}" = "${SCRIPT_HOME}/../ant/lib/${ANT_VERSION}/:" ]
then
	noAntJars
fi

# Hate preceeding colons in paths...
if [ "${USER_CLASSPATH}" = "" ]
then
	CLASSPATH="${ANT_CLASSPATH}"
else
	CLASSPATH="${USER_CLASSPATH}:${ANT_CLASSPATH}"
fi

# Kick off ant...
java -classpath ${CLASSPATH} -Dant.home=${SCRIPT_HOME}/../ant org.apache.tools.ant.Main -f ${USER_FILE} ${SOLENOPSIS_ARGS}